resources:
  - name: basic_aspnetcore_gitRepo
    type: gitRepo
    integration: dr_gh
    versionTemplate:
      sourceName: rageshkrishna/basic_aspnetcore
      branch: master

  - name: basic_aspnetcore_image
    type: image
    integration: drship_dockerhub
    versionTemplate:
      sourceName: ragesh/basic_aspnetcore
      versionName: latest

jobs:
  - name: build
    type: runSh
    integrations:
      - drship_dockerhub
    steps:
      - IN: basic_aspnetcore_gitRepo
      - TASK:
          runtime:
            options:
              imageName: drydock/w16aspnetcore
              imageTag: v6.8.4
              env:
                - DOCKER_ACC: ragesh
                - DOCKER_REPO: basic_aspnetcore
                - RES_OUT_IMG: basic_aspnetcore_image
          script:
            - pushd $(shipctl get_resource_state basic_aspnetcore_gitRepo)
            - dotnet restore
            - dotnet publish -c Release -o out
            - |
               # Set up DOCKER_HOST so we can run a docker build
               $gateway = ((Get-NetRoute | where {$_.DestinationPrefix -eq '0.0.0.0/0'}).NextHop)
               $env:DOCKER_HOST="tcp://${gateway}:2375"
            - $IMG_NAME=$(shipctl get_resource_version_key "$env:RES_OUT_IMG" "sourceName")
            - echo "${IMG_NAME}:${BUILD_NUMBER}"
            - docker build -t="${IMG_NAME}:${BUILD_NUMBER}" .
            - |
               # Log in to Docker Hub
               $DH_USR_NAME=$(shipctl get_integration_resource_field "$env:RES_OUT_IMG" "userName")
               $DH_PASS=$(shipctl get_integration_resource_field "$env:RES_OUT_IMG" "password")
               docker login -u $DH_USR_NAME -p $DH_PASS
            - docker push $image
      - OUT: basic_aspnetcore_image
    on_success:
      script:
        # Update OUT resource to create a new version that will trigger rest of the workflow
        - shipctl put_resource_state_multi "$env:RES_OUT_IMG" "versionName=$BUILD_NUMBER"